[SQ-17398] insp.has_table() with no catalog permissions
SQream/pysqream_sqlalchemy pull request #21
Opened 2024-05-29 12:11 UTC by eugenek-sqream

https://sqream.atlassian.net/browse/SQ-17398

2024-05-29 20:21 UTC, danielg-sqream requested changes
You should support also the get_table_names of previous version of SQream

2024-05-29 20:41 UTC, eugenek-sqream commented
@danielg-sqream I didn't touch get_table_names function.
So if you r talking about the old version of has_table function, I've declared the minimum version of SQream especially for this package, so if someone uses the old db version, he also can use a previous version package, isn't it? :)
Please contact Efrat to clarify do we need old stuff support in new package or not, as I understood - no.

2024-05-30 09:34 UTC, eugenek-sqream commented
@danielg-sqream please merge and release the package :)
https://sqream.atlassian.net/browse/SQ-17398

2024-05-30 11:23 UTC, danielg-sqream approved these changes

2024-05-30 11:23 UTC, merged